import images from "./assets/img";

const projects = [
  {
    id: 1,
    name: "RESIDENCIA DECALISE",
    image: images.imgFrontPinilla,
    m2: "440",
    location: "SANTACRUZ GUANACASTE",
    address: "HACIENDA PINILLA RESIDENCIAL GOLONDRINAS",
    render1: images.imgBackPinilla,
    render2: images.imgBack2Pinilla,
    render3: images.imgRightPinilla,
    render4: images.imgElevacionPinilla,
    render5: images.imgElevacion2Pinilla,
  },
  {
    id: 2,
    name: "RESIDENCIA H10",
    image: images.ImgResidenciaH10,
    m2: "660",
    location: "SANTANA SAN JOSE",
    address: "ECO RESIDENCIAL VILLAREAL",
  },
  {
    id: 3,
    name: "CASA LUNA DOBLADA",
    image: images.ejemplo,
    m2: "170",
    location: "SANTANA SAN JOSE",
    address: "RIO ORO",
  },
  {
    id: 4,
    name: "CASA DE HABITACION OSCAR",
    image: images.ejemplo,
    m2: "100",
    location: "HATILLO SAN JOSE",
    address: "URBANIZACION HATILLO 4",
  },
  {
    id: 5,
    name: "CASA EN EL AIRE",
    image: images.ejemplo,
    m2: "270",
    location: "OROTINA PUNTARENAS",
    address: "ECO RESIDENCIAL ALEGRIA",
  },
  {
    id: 6,
    name: "TINY HOUSE",
    image: images.ejemplo,
    m2: "100",
    location: "DOMINICALITO PUNTARENAS",
    address: "CALLE ESCALERAS",
  },
  {
    id: 7,
    name: "CASA PABLO Y WENDY",
    image: images.ejemplo,
    m2: "60",
    location: "SAN ISIDRO HEREDIA",
    address: "URBANIZACION",
  },
  {
    id: 8,
    name: "CASA KATHERINE",
    image: images.ejemplo,
    m2: "100",
    location: "DESAMPARADOS ALAJUELA",
    address: "URBANIZACION",
  },
];

export default projects;
