import images from "./assets/img";

const proyectsRemodelacion = [
  {
    remodelacion: "projectsRemodelacion",
    id: 9,
    name: "Terraza Taller de Danza",
    image: images.ejemplo,
    tamaño: "200 m²",
    location: "Coronado San Jose",
    address: "Eco Residencial Villareal",
    category: "Movimiento de Tierras",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 10,
    name: "Remodelación de Fachada Quepos",
    image: images.ejemplo,
    tamaño: "250 m²",
    location: "Quepos Puntarenas",
    category: "Remodelación General",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 11,
    name: "Remodelación Casa Sharon",
    image: images.ejemplo,
    tamaño: "250 m²",
    location: "San Rafael Heredia",
    category: "Remodelación General",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 12,
    name: "Residencia Los Pargos",
    image: images.ejemplo,
    tamaño: "350 m²",
    location: "Playa Negra Guanacaste",
    category: "Reparación de Cubiertas",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 13,
    name: "Casa Marcos",
    image: images.ejemplo,
    tamaño: "250 m²",
    location: "San Rafael Heredia",
    category: "Construcción Segundo Nivel",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 14,
    name: "Remodelación Buble Tea",
    image: images.ejemplo,
    tamaño: "100 m²",
    location: "Sabana San Jose",
    category: "Remodelación de Restaurante",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 15,
    name: "Trabajos El Mercadito",
    image: images.ejemplo,
    tamaño: "40 m²",
    location: "Tamarindo Guanacaste",
    category: "Reestructuración Eléctrica",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 16,
    name: "Remodelación Edificio Alejandro",
    image: images.ejemplo,
    tamaño: "300 m²",
    location: "Sabana San Jose",
    category: "Remodelación General",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 17,
    name: "Remodelación Apartamentos Alejandro",
    image: images.ejemplo,
    tamaño: "80 m²",
    location: "Escazu San Jose",
    category: "Remodelación General",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 18,
    name: "Remodelación Tropical Studios",
    image: images.ejemplo,
    tamaño: "100 m²",
    location: "La Paco Escazu",
    category: "Remodelación General",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 19,
    name: "Residencia 48 Cerro Real",
    image: images.ejemplo,
    tamaño: "600 m²",
    location: "Alto de las Palomas",
    category: "Construcción Planta de Tratamiento",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 20,
    name: "Construcción de Cerramiento Huacas",
    image: images.ejemplo,
    tamaño: "100 m²",
    location: "Huacas Guanacaste",
    category: "Construcción de Tapias",
  },
  {
    remodelacion: "projectsRemodelacion",
    id: 21,
    name: "Construcción de Losas de Concreto",
    image: images.ejemplo,
    tamaño: "200 m²",
    location: "Desamparados Alajuela",
    category: "Colocación de Losas de Concreto",
  },
];

export default proyectsRemodelacion;
