import images from "./assets/img";

const projects = [
  {
    id: 1,
    name: "Residencia Decalise",
    image: images.imgFrontPinilla,
    tamaño: "440 m²",
    location: "Santacruz Guanacaste",
    address: "Hacienda Pinilla Residencial Golondrinas",
    category: "Edificación",
    render1: images.imgBackPinilla,
    render2: images.imgBack2Pinilla,
    render3: images.imgRightPinilla,
    render4: images.imgElevacionPinilla,
    render5: images.imgElevacion2Pinilla,
  },
  {
    id: 2,
    name: "Residencia H10",
    image: images.ImgResidenciaH10,
    tamaño: "660 m²",
    location: "Santana San Jose",
    address: "Eco Residencial Villareal",
    category: "Edificación",
  },
  {
    id: 3,
    name: "Casa Luna Doblada",
    image: images.ejemplo,
    tamaño: "170 m²",
    location: "Santana San Jose",
    address: "Rio Oro",
    category: "Edificación",
  },
  {
    id: 4,
    name: "Casa de Habitacion Oscar",
    image: images.ejemplo,
    tamaño: "100 m²",
    location: "Hatillo San Jose",
    address: "Urbanizacion Hatillo 4",
    category: "Edificación",
  },
  {
    id: 5,
    name: "Casa en el Aire",
    image: images.ejemplo,
    tamaño: "270 m²",
    location: "Orotina Puntarenas",
    address: "Eco Residencial Alegria",
    category: "Edificación",
  },
  {
    id: 6,
    name: "Tiny House",
    image: images.ejemplo,
    tamaño: "100 m²",
    location: "Dominicalito Puntarenas",
    address: "Calle Escaleras",
    category: "Edificación",
  },
  {
    id: 7,
    name: "Casa Pablo y Wendy",
    image: images.ejemplo,
    tamaño: "60 m²",
    location: "San Isidro Heredia",
    address: "Urbanizacion",
    category: "Edificación",
  },
  {
    id: 8,
    name: "Casa Katherine",
    image: images.ejemplo,
    tamaño: "100 m²",
    location: "Desamparados Alajuela",
    address: "Urbanizacion",
    category: "Edificación",
  },
];

export default projects;
